// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adzaejrtirjismbfqmwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkemFlanJ0aXJqaXNtYmZxbXdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDg4MTMsImV4cCI6MjA2NTQyNDgxM30.wrdmpozDrxHbdjm3cs7U47KTD94vgjtnpT8htZQlkkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);